"""Regenerate agents/README.md from the agent specs, so the table never drifts from what is loaded.
Usage: python scripts/agents_doc.py"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODEL = {"$SMALL": "small", "$STRONG": "strong"}

rows = []
for f in sorted((ROOT / "agents").glob("ns-*.json")):
    spec = json.loads(f.read_text())
    m = spec["manifest"]
    tools = "<br>".join(f"{s['name']}: {', '.join(s.get('enable_tools', []))}" for s in m.get("mcp_servers", [])) or "–"
    gated = ", ".join(f"`{t}`" for s in m.get("mcp_servers", []) for t in s.get("require_approval_for_tools", [])) or "–"
    cfg = m.get("config", {})
    runtime = ", ".join(x for x, on in (("sandbox", cfg.get("sandbox", {}).get("enabled")),
                                         ("sub-agents", cfg.get("dynamic_sub_agents", {}).get("enabled"))) if on) or "–"
    schema = m.get("response_format", {}).get("json_schema", {}).get("schema", {})
    must = ", ".join(f"`{k}`" for k in schema.get("required", []))
    rows.append(f"| `{spec['name']}` | {spec['description']} | {MODEL.get(m['model']['name'], m['model']['name'])} | {tools} | {gated} | {runtime} | {must} |")

(ROOT / "agents/README.md").write_text(f"""# NightShift agents

{len(rows)} saved TrueForge agents, one job each. `scripts/setup_trueforge.py` loads these files into TrueForge (create or
update) and fills in the models configured there: **small** = fast and cheap for routine steps (MiniMax M2.5 on Bedrock),
**strong** = for diagnosis, planning, code and anything that changes production (Kimi K3 on Bedrock). Override one agent's
model with `NS_MODEL_<AGENT>` in `.env`, e.g. `NS_MODEL_NS_CODER=bedrock/kimi-k3`.

Every agent answers with one JSON object matching its schema, always including `summary` and `confidence`, so the
orchestrator can chain them without parsing prose. This file is generated by `scripts/agents_doc.py`.

| Agent | Job | Model | Tools it may use | Pauses for approval before | Runtime | Must return |
|---|---|---|---|---|---|---|
""" + "\n".join(rows) + """

## Safety rules built into every agent

- Tools that change the system are listed **by name** under "pauses for approval". TrueForge stops the call and NightShift
  asks a person on Jira or the dashboard, showing the live error rate, the planner's risk and evidence, and how to undo it.
  Unanswered approvals expire as denied after `APPROVAL_TIMEOUT_MIN` (default 30).
- Agents get only the tools their job needs. Diagnosis can read everything but change nothing.
- Code runs only in TrueForge's Daytona sandbox, which has no secrets and no access to the live system.
- Evidence must be quoted from real tool output: the orchestrator checks every quote and marks the rest unverified.
  A PR link or a promoted canary is only accepted if the real tool returned it.
- Tools missing in a deployment are named in the agent's instructions, so it does not waste calls looking for them.
""")
print(f"agents/README.md: {len(rows)} agents")
