"""Build the system map: what each service is, what it serves, whom it calls, where its code lives.

Agents get this up front, so they do not spend tool calls rediscovering the architecture in every incident.
Run it once when a system is onboarded, and again after big changes:
    .venv/bin/python scripts/map_system.py [astronomy-shop]
It reads the system's repo (local_path in systems/<name>.yaml) and writes systems/<name>.map.md.
Only names of settings are recorded, never their values.
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = {".js", ".ts", ".tsx", ".go", ".py", ".cs", ".java", ".kt", ".rs", ".rb", ".php", ".cpp", ".cc", ".h"}
SKIP_DIRS = {"node_modules", "vendor", "bin", "obj", "build", "dist", "target", ".git", "__pycache__", "genproto", "pb", "proto"}


def proto_services(repo: Path, shared: list[str]) -> dict[str, list[str]]:
    """gRPC services and their methods from the shared .proto contracts."""
    out: dict[str, list[str]] = {}
    for d in shared:
        for f in (repo / d).rglob("*.proto") if (repo / d).exists() else []:
            current = None
            for line in f.read_text(errors="ignore").splitlines():
                m = re.match(r"\s*service\s+(\w+)", line)
                if m:
                    current = m.group(1)
                    out[current] = []
                m = re.match(r"\s*rpc\s+(\w+)", line)
                if m and current:
                    out[current].append(m.group(1))
    return out


def service_for_proto(name: str, services: dict) -> str | None:
    base = re.sub(r"Service$", "", name)
    kebab = re.sub(r"(?<!^)(?=[A-Z])", "-", base).lower()
    return kebab if kebab in services else None


def compose_env(repo: Path, files: list[str]) -> dict[str, list[str]]:
    """Setting names per compose service (values are left out on purpose)."""
    env: dict[str, set[str]] = {}
    for f in files:
        p = repo / f
        if not p.exists():
            continue
        data = yaml.safe_load(p.read_text()) or {}
        for name, svc in (data.get("services") or {}).items():
            e = svc.get("environment") or []
            keys = e.keys() if isinstance(e, dict) else [str(x).split("=")[0] for x in e]
            env.setdefault(name, set()).update(k for k in keys if k)
    return {k: sorted(v) for k, v in env.items()}


def key_files(folder: Path, limit: int = 10) -> list[str]:
    if not folder.exists():
        return []
    files = []
    for p in sorted(folder.rglob("*")):
        rel = p.relative_to(folder)
        if any(part in SKIP_DIRS for part in rel.parts) or not p.is_file() or p.suffix not in SOURCE:
            continue
        if re.search(r"(test|spec|_pb|\.pb\.|generated)", p.name, re.I):
            continue
        files.append((p.stat().st_size, str(rel)))
    # the biggest source files are usually the service's core
    return [f for _, f in sorted(files, reverse=True)[:limit]]


def tests_of(folder: Path) -> list[str]:
    if not folder.exists():
        return []
    return sorted(str(p.relative_to(folder)) for p in folder.rglob("*")
                  if p.is_file() and re.search(r"(test|spec)", p.name, re.I) and not any(x in SKIP_DIRS for x in p.parts))[:6]


def flags_for(repo: Path, flag_file: str, service: str, folder: Path) -> list[str]:
    p = repo / flag_file
    if not p.exists() or not folder.exists():
        return []
    flags = json.loads(p.read_text()).get("flags", {})
    code = " ".join(f.read_text(errors="ignore") for f in folder.rglob("*") if f.is_file() and f.suffix in SOURCE and f.stat().st_size < 400_000
                    and not any(x in SKIP_DIRS for x in f.parts))
    return [f"{n} ({v.get('description', '')})" for n, v in flags.items() if n in code]


def main() -> None:
    name = sys.argv[1] if len(sys.argv) > 1 else "astronomy-shop"
    system = yaml.safe_load((ROOT / "systems" / f"{name}.yaml").read_text())
    repo = (ROOT / system["repo"].get("local_path", "")).resolve()
    services = system["services"]
    shared = system.get("shared_paths", [])
    protos = proto_services(repo, shared)
    env = compose_env(repo, system.get("runtime", {}).get("compose_files", []))
    serves: dict[str, list[str]] = {}
    for proto, rpcs in protos.items():
        svc = service_for_proto(proto, services)
        if svc:
            serves[svc] = [f"{proto}.{r}" for r in rpcs]
    callers: dict[str, list[str]] = {}
    for s, spec in services.items():
        for d in spec.get("depends_on", []):
            callers.setdefault(d, []).append(s)

    lines = [f"# System map: {name}", "",
             f"Generated by scripts/map_system.py from {system['repo']['url']}. Architecture for the agents; check code before relying on details.", "",
             f"Domain: {system.get('domain', '')}. Shared code: {', '.join(shared) or 'none'} (protobuf contracts and libraries used by several services).", "",
             "## Request flow", ""]
    for s, spec in services.items():
        if spec.get("depends_on"):
            lines.append(f"- {s} calls {', '.join(spec['depends_on'])}")
    for s, spec in services.items():
        folder = repo / spec.get("path", "")
        lines += ["", f"## {s}", "",
                  f"- Language: {spec.get('language')}; code: `{spec.get('path')}`" + (f"; tests: `{spec['test_cmd']}`" if spec.get("test_cmd") else ""),
                  ]
        if serves.get(s):
            lines.append(f"- Serves: {', '.join(serves[s])}")
        if spec.get("depends_on"):
            lines.append(f"- Calls: {', '.join(spec['depends_on'])}")
        if callers.get(s):
            lines.append(f"- Called by: {', '.join(callers[s])}")
        if env.get(s):
            lines.append(f"- Settings (names only): {', '.join(env[s][:18])}")
        kf = key_files(folder)
        if kf:
            lines.append(f"- Main source files: {', '.join(kf)}")
        tf = tests_of(folder)
        if tf:
            lines.append(f"- Existing tests: {', '.join(tf)}")
        fl = flags_for(repo, system.get("flags", {}).get("file", ""), s, folder)
        if fl:
            lines.append(f"- Failure switches in its code: {'; '.join(fl)}")
    out = ROOT / "systems" / f"{name}.map.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(ROOT)}: {len(services)} services, {len(lines)} lines, {len(out.read_text())} characters")


if __name__ == "__main__":
    main()
